### ISSUE TITLE
postgresql_role & postgresql_database signal SIGSEGV: segmentation violation code

### ISSUE THREAD

**Issue by tristandibbens** [cyrilgdn/terraform-provider-postgresql#120]
Hi,

This is my first ever post on Git, so please forgive me if not following any particular protocols.

I am using Terraform 1.0.0 with this postgres provider 1.13.0

Backend file is here:

terraform {
  backend "s3" {
    encrypt = true
  }
  required_version = "~> 1.0.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.46.0"
    }
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "~> 1.13.0"
    }
  }
}
provider "postgresql" {
  scheme           = "awspostgres"
  host             = aws_db_instance.d3.address
  port             = 5432
  username         = data.aws_ssm_parameter.db_username.value
  password         = data.aws_ssm_parameter.db_password.value
  superuser        = false
  expected_version = aws_db_instance.d3.engine_version
}

I'm using this on a db with encryption added:

resource "postgresql_role" "django" {
  name     = var.fargate_services.database_username
  password = data.aws_ssm_parameter.fargate_db_password.value
  login    = true
}

resource "postgresql_database" "mydata3" {
  name  = "mydata3"
  owner = "django"
}

In running this I repeatedly get the following error - what else might you need to trouble shoot? 

│ Error: Plugin did not respond
│
│   with postgresql_role.django,
│   on rds.tf line 85, in resource "postgresql_role" "django":
│   85: resource "postgresql_role" "django" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with postgresql_database.mydata3,
│   on rds.tf line 91, in resource "postgresql_database" "mydata3":
│   91: resource "postgresql_database" "mydata3" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-postgresql_v1.13.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd7affa]

goroutine 26 [running]:
database/sql.(*Tx).grabConn(0x0, 0x12537a0, 0xc00003c0a8, 0x10, 0xc0001f62f0, 0x17ddde0, 0xc00013ec00)
        database/sql/sql.go:2112 +0x5a
database/sql.(*Tx).ExecContext(0x0, 0x12537a0, 0xc00003c0a8, 0x10b0a97, 0x4a, 0xc0007575c0, 0x1, 0x1, 0xc00006c1e0, 0xc0007d4000, ...)
        database/sql/sql.go:2362 +0x4c
database/sql.(*Tx).Exec(...)
        database/sql/sql.go:2372
github.com/terraform-providers/terraform-provider-postgresql/postgresql.pgLockRole(0x0, 0xc00003ddf8, 0x4, 0x0, 0x123eba0)
        github.com/terraform-providers/terraform-provider-postgresql/postgresql/helpers.go:447 +0xd1
github.com/terraform-providers/terraform-provider-postgresql/postgresql.createDatabase(0xc000224360, 0xc0002f0850, 0x0, 0x0)
        github.com/terraform-providers/terraform-provider-postgresql/postgresql/resource_postgresql_database.go:128 +0x157c
github.com/terraform-providers/terraform-provider-postgresql/postgresql.resourcePostgreSQLDatabaseCreate(0xc000224360, 0xc0002f0850, 0x0, 0x0)
        github.com/terraform-providers/terraform-provider-postgresql/postgresql/resource_postgresql_database.go:110 +0x39
github.com/terraform-providers/terraform-provider-postgresql/postgresql.PGResourceFunc.func1(0xc0002f0850, 0xf22540, 0xc0000ac5a0, 0x2, 0x1826b20)
        github.com/terraform-providers/terraform-provider-postgresql/postgresql/helpers.go:22 +0x8e
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0000b5280, 0xc0001fc820, 0xc0002bc420, 0xf22540, 0xc0000ac5a0, 0xf35201, 0xc0000960f8, 0xc0001feed0)
        github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/resource.go:305 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000b5700, 0xc000757a38, 0xc0001fc820, 0xc0002bc420, 0xc0002283e8, 0xc00000fc58, 0xf371e0)
        github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/provider.go:289 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000f2a0, 0x1253810, 0xc0001fe090, 0xc000195f20, 0xc00000f2a0, 0xc0001fe090, 0xc000824ba0)
        github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/helper/plugin/grpc_provider.go:885 +0x88b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1032620, 0xc00000f2a0, 0x1253810, 0xc0001fe090, 0xc000195ec0, 0x0, 0x1253810, 0xc0001fe090, 0xc0001c6300, 0x164)
        github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00023b180, 0x125e1b8, 0xc000820f00, 0xc0001ecf00, 0xc000100870, 0x17e70e0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.34.0/server.go:1210 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00023b180, 0x125e1b8, 0xc000820f00, 0xc0001ecf00, 0x0)
        google.golang.org/grpc@v1.34.0/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004e42c0, 0xc00023b180, 0x125e1b8, 0xc000820f00, 0xc0001ecf00)
        google.golang.org/grpc@v1.34.0/server.go:871 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.34.0/server.go:869 +0x1fd

Error: The terraform-provider-postgresql_v1.13.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by tristandibbens** [comment]
Re ran without encrypted database and it ran perfectly.  Any ideas what I can do to allow the encryption to work with this plugin?

**Comment by tristandibbens** [comment]
> 
> 
> Re ran without encrypted database and it ran perfectly. Any ideas what I can do to allow the encryption to work with this plugin?

Any thoughts on this at all?
